server:
  port: 8080

spring:
  application:
    name: TimeLoitDemo

  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multi_table_join?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    druid:
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        session-stat-enable: true
        enabled: true


  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #标注实体类位置
  type-aliases-package: com.rawchen.multitablejoi.entity
  configuration:
    #开启mybatis驼峰式命名规则自动转换
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    #控制台打印mapper接口的sql语句日志
    com.rawchen.multitablejoin.mapper: debug